Add Explorer to the default Saleor Playground
saleor/saleor-graphql-playground pull request #5
Opened 2023-01-02 13:05 UTC by zaiste

2023-01-02 13:24 UTC, mmiszy approved these changes

2023-01-02 21:11 UTC, mmiszy requested changes

2023-01-02 21:11 UTC, mmiszy commented on README.md
> +npm run dev
```suggestion
pnpm run dev
```

2023-01-03 11:01 UTC, zaiste commented on README.md
> +npm run dev
@mmiszy done

2023-01-03 13:07 UTC, mmiszy approved these changes

2023-01-03 17:17 UTC, merged